mx.gob.imss.dpes.pensionadoback.restclient.PersonaClient/mp-rest/url=http://localhost/serviciosDigitales/webresources
mx.gob.imss.dpes.pensionadoback.restclient.PensionadoSistrapClient/mp-rest/url=http://localhost/sistrap/webresources
mx.gob.imss.dpes.pensionadoback.restclient.PensionClient/mp-rest/url=http://localhost/sistrap/webresources


